### PR TITLE
Update xilpm requirements

### PR DESCRIPTION
**Pull request by bentheredonethat**
remove old lop files and make more data driven approach from information propagated from lopper-input SDT

### CODE REVIEW

**Comment by bentheredonethat** [comment]
i can clean up commit messages for this pull request

**Comment by bentheredonethat** [comment]
updated commit messages and order of commits

**Comment by bentheredonethat** [comment]
@zeddii  can you review this when able?

**Comment by zeddii** [comment]
I have already scanned it once, and it looks ok.  

Lopper is going through an abstraction from libfdt and that has exposed some issues, and I've been dealing with that fallout.

Is there a full cut and paste line that you can provide for a sample run of lopper with these updated assists ? That way I can test against the new WIP code before merging.

**Comment by zeddii** [comment]
There are still issues lurking due to the scope of the fdt abstraction changes, but I was able to run this and get the same output. Sanity is passing as well, so I've pushed this along with the fdt changes.

**Pull request closed without merging**
