### PR TITLE
Update cdo parsing

### PR DESCRIPTION
**Pull request by bentheredonethat**
- yaml -> dts now matches spec
- update cdo plugin to use latest generated SDT per YAML expansion

### CODE REVIEW

**Comment by zeddii** [comment]
I've been having a look at this, and want to consider a few more things. 

I wanted to comment, so you'd know that I didn't miss this!

**Comment by bentheredonethat** [comment]
@zeddii  ping for update

**Comment by zeddii** [comment]
Still the same as 2 days ago. reviewing and testing. There are interactions with other pending changes.

**Comment by zeddii** [comment]
I'm finishing up a generalized description language that would simplify some of the assists by allowing us to describe the yaml flags -> DTS flags, without needing to write as much python code.

But that is taking a bit longer than I'd like, so I've gone ahead and merged this.

We can adjust as necessary once I get that code completed.

**Pull request merged**
