### PR TITLE
assists: baremetal_xparameters: Generate Canonical definitions for IPI targets

### PR DESCRIPTION
**Pull request by Harini-T**
Current implementation doesnt generate canonical definitions for IPI targets.

Generate Canonical definitions of IPI Bitmask and Buffer Index for the available IPI targets.

@onkarharsh @kedareswararao can you please review ?

### CODE REVIEW

**Comment by kedareswararao** [comment]
Changes looks fine to me

**Review by onkarharsh — CHANGES_REQUESTED** [review]
Hi Harini, Please send v2 as discussed offline.
1. Try to avoid using ip-name in here, instead use drv name. We may miss updating ip names here with new platforms.
2. Try reducing lines of code by using a new if condition within existing child,required condition. Repetition of loop should be fine.

**Comment by Harini-T** [comment]
Hi @onkarharsh @kedareswararao 
I have sent v2 in the same pull request
Can you please review it?

**Comment by onkarharsh** [comment]
Change looks fine now

**Review by kedareswararao — APPROVED** [review]
Changes looks fine.

**Pull request merged**
