### PR TITLE
lopper: assists: gen_domain_dts: Add option to prune TCM nodes

### PR DESCRIPTION
**Pull request by bentheredonethat**
Add option that if present allows user to prune TCM DT nodes.

To remove TCM nodes, add third option on command line for this assist.

### CODE REVIEW

**Comment by zeddii** [comment]
I'm ok with the change, but a couple of things did jump to mind.

As long as you are ok with not using a -- type option, I'm ok with it (i.e. humans aren't going to mess up the command line).

And a second thought, what the conditions where these should and shouldn't be pruned ? Is this something we could pick up programmatically ?

**Comment by kedareswararao** [comment]
@bentheredonethat : instead of keeping tcm nodes default please delete it default and have them in case of openmap use case, please update the changes accordingly. 

CC: @onkarharsh

**Comment by bentheredonethat** [comment]
> @bentheredonethat : instead of keeping tcm nodes default please delete it default and have them in case of openmap use case, please update the changes accordingly.
> 
> CC: @onkarharsh

what do you mean here?

what is a valid check? because this means that one assist has to be aware of the other effectively having been run.

**Comment by bentheredonethat** [comment]
@kedareswararao  @onkarharsh  we need tcm nodes for openamp case
that is why i added switch
we can have the switch present by default

**Comment by kedareswararao** [comment]
@bentheredonethat and @zeddii : latest changes looks fine to me.

Regards,
Kedar.

**Pull request merged**
