### PR TITLE
demo: openamp: Make openamp demo work

### PR DESCRIPTION
**Pull request by tnmysh**
Fix README.md file lopper demo as per 2024.2 latest lopper release. Introduce new yaml in inputs directory again for demo purpose.

### CODE REVIEW

**Comment by zeddii** [comment]
The only part of this that is problematic is the Pipfile change.

I'm not seeing issues with the current Pipfile/pipenv, so I need to understand why you needed those additions for lopper to function.

Then we'd need to split that into a separate commit with an appropriate commit log.

**Comment by tnmysh** [comment]
Okay, I don’t think Pipfile changes are needed.

May be my system is old. I was running on Ubuntu20.04, now updated to Ubuntu-22.04.

I will remove Pipfile changes in PR.

**Comment by zeddii** [comment]
I see a new commit was pushed, but the pipfile change is still there. Was this just an intermediate push and this isn't ready for re-review yet ?

I'd also want @bentheredonethat  to have a look at the final pull request before merging.

**Comment by bentheredonethat** [comment]
not reviewed -- also @tnmysh  for what exact case is this?

**Comment by tnmysh** [comment]
> I see a new commit was pushed, but the pipfile change is still there. Was this just an intermediate push and this isn't ready for re-review yet ?
> 

I am not sure what's wrong. My push should have updated that file.

> I'd also want @bentheredonethat to have a look at the final pull request before merging.

**Comment by tnmysh** [comment]
@zeddii  this PR is ready now. Fixed Pipfile as requested.

**Comment by tnmysh** [comment]
> not reviewed -- also @tnmysh for what exact case is this?

@bentheredonethat to give you some background. OpenAMP project has some demos to show overall open-amp functionality on various platforms. Lopper has one demo as well. Please see here for the documentation: https://openamp.readthedocs.io/en/latest/lopper/demos/openamp/README.html

Above demo was introduced in 2022, and since then it's using lopper version from 2022 release.

Now lopper has new features and task here is to update lopper version to 2024 latest master branch.

This PR is doing exactly that, and adding missing parts to make that demo work.

Feel free to ask any further questions on that.

**Comment by bentheredonethat** [comment]
LGTM @zeddii  @tnmysh

**Pull request merged**
