### PR TITLE
xilinx: Bug fixes and enhancements 

### PR DESCRIPTION
**Pull request by kedareswararao**
Hi,

This pull request does the below
1) Created new lops file for zynq ultrascale a53 linux domain
2) Bug fixes in the baremetal assist file
3) Updated the A72 domain lops file as per latest system dt spec

### CODE REVIEW

**Comment by zeddii** [comment]
I haven't forgotten about this. I was just sorting out some issues with yaml and REST APIs, but will get to this shortly.

**Comment by kedareswararao** [comment]
> I haven't forgotten about this. I was just sorting out some issues with yaml and REST APIs, but will get to this shortly.

That's fine @zeddii ... 

Regards,
Kedar.

**Comment by zeddii** [comment]
rebased and merged. Sorry for the delay!

**Comment by kedareswararao** [comment]
> rebased and merged. Sorry for the delay!

No issues... Thanks for merging the changes @zeddii  

Regards,
Kedar.

**Pull request closed without merging**
